name: tEST Latest Android NDK and SDK ID

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fetch-latest-ndk-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK Command-line Tools
        run: |
          sudo mkdir -p /opt/android-sdk/cmdline-tools/latest
          cd /opt/android-sdk/cmdline-tools/latest
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip sdk-tools.zip
          rm sdk-tools.zip
          echo "export ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Get Latest Android SDK ID
        run: |
          sdkmanager --list | grep "platforms;android-" | awk '{print $1}' | sort -V | tail -n 1 | tee latest_sdk_id.txt

      - name: Get Latest Android NDK ID
        run: |
          sdkmanager --list | grep "ndk;" | awk '{print $1}' | sort -V | tail -n 1 | tee latest_ndk_id.txt

      - name: Upload SDK and NDK IDs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: latest-android-ids
          path: |
            latest_sdk_id.txt
            latest_ndk_id.txt
