name: Get Latest Android SDK ID

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  get_sdk_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Android SDK tools
        uses: android-actions/setup-android@v3
        with:
          command-line-tools: "latest"

      - name: Get latest platform API level
        id: get_api_level
        run: |
          latest_api_level=$( $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list | grep "platforms;android-" | sort -r | head -n 1 | awk -F ';' '{print $2}' | awk -F '-' '{print $2}')
          echo "latest_api_level=$latest_api_level" >> $GITHUB_OUTPUT

      - name: Display latest API level
        run: | 
             echo "Latest Android API level:"
             echo  ${{ steps.get_api_level.outputs.latest_api_level }}

      - name: Get Latest build tools version
        id: get_build_tools
        run: |
          latest_build_tools=$( $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list | grep "build-tools;" | sort -r | head -n 1 | awk -F ';' '{print $2}')
          echo "latest_build_tools=$latest_build_tools" >> $GITHUB_OUTPUT

      - name: Display latest build tools version
        run: | 
            echo "Latest Android build tools version: 
            echo ${{ steps.get_build_tools.outputs.latest_build_tools }}"

      - name: Get latest NDK version
        id: get_ndk_tools
        run: |
          latest_ndk=$( $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list | grep "ndk;" | sort -r | head -n 1 | awk -F ';' '{print $2}')
          echo "latest_ndk=$latest_ndk" >> $GITHUB_OUTPUT

      - name: Display latest NDK version
        run: | 
          echo "Latest Android NDK version:"
          echo ${{ steps.get_ndk_tools.outputs.latest_ndk }}
