name: Update Android SDK

on:
  push:
    branches:
      - main
      - latest-sdk

  workflow_dispatch:

jobs:
  Update-Android-SDK:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Base Repository
        id: initialize_repository
        run: |
          git clone https://github.com/ovsky/adb-fastboot-installer.git      

      - name: Download latest SDK .zip file
        id: manage_sdk_files
        run: wget -O sdk.zip ${{ secrets.ANDROID_SDK_URL }}
        
      - name: Unpack .ZIP file
        run: |
          curl -s https://developer.android.com/studio#command-tools | grep -oE 'https://dl.google.com/android/repository/commandlinetools-linux-[0-9]+_latest.zip' | head -n 1 | xargs curl -O
          chmod 777 adb-fastboot-installer
          rm -rf adb-fastboot-installer/.git
          rm -rf adb-fastboot-installer/.github/workflows
          unzip -o sdk.zip -d ./adb-fastboot-installer/
          mv  -v ./adb-fastboot-installer/platform-tools/* ./adb-fastboot-installer/adb
          rm sdk.zip

      - name: Get all branch names
        id: get_branches
        run: |
          branch_names=$(git branch --remote | grep origin/ | grep -v HEAD | sed 's/origin\///')
          echo "BRANCH_NAMES=$branch_names" >> "$GITHUB_OUTPUT"
          echo $branch_names

      - name: Parse branch names and find highest number
        id: parse_branches
        run: |
          branch_names="${{ steps.get_branches.outputs.BRANCH_NAMES }}"
          highest_number=0

          if [[ -n "$branch_names" ]]; then
            for branch in $branch_names; do
              number=$(echo "$branch" | grep -o '[0-9]\+$') #Extracts the number at end of branch name.
              if [[ -n "$number" ]]; then
                if [[ "$number" -gt "$highest_number" ]]; then
                  highest_number="$number"
                fi
              fi
            done
          fi

          echo "HIGHEST_NUMBER=$highest_number" >> "$GITHUB_OUTPUT"

      - name: Echo highest number
        run: |
          echo "Highest branch number: ${{ steps.parse_branches.outputs.HIGHEST_NUMBER }}"

      - name: Check Secrets
        run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SDK_CHECKER: ${{secrets.SDK_CHECKER}}
          SDK_BRANCH: ${{secrets.ANDROID_SDK_BRANCH}}

      - name: Analyze latest SDK versions
        id: fetch_sdk_id
        run: |
          response=$(curl -s ${{ secrets.SDK_CHECKER }})
          short=$(curl -s ${{ secrets.ANDROID_SDK_BRANCH }})
          sdk_id=$(echo $response)
          branch_id=$(echo $short)
          echo "SDK_ID=$sdk_id" >> $GITHUB_ENV
          echo "BRANCH_ID=$branch_id" >> $GITHUB_ENV
          echo "$sdk_id" > ./adb-fastboot-installer/SDK-VERSION.txt

      - name: Display SDK_ID and BRANCH_ID
        run: |
          echo "Current SDK_ID is:"
          echo $SDK_ID
          echo "Current API is:"
          echo $BRANCH_ID

      - name: Deploy Android SDK Update 
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: auto-update-${{ env.BRANCH_ID }}
          FOLDER: adb-fastboot-installer
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Update API: ${{ env.SDK_ID }} [{sha}]" 
          SQUASH_HISTORY: true
          COMMIT_NAME: Auto Update (${{ env.SDK_ID }})

